tools:
  jdk:
    flavor: azul
    version: 11
  maven: 3.6.1
envs:
  global:
    variables:
      deployVersion: "N/A"
      deployArtifactId: "N/A"
      ALLOW_ARTIFACTORY: true
triggers:
  - push: disabled
  - pr:
      call: pr-build
  - manual:
      name: build
      call: default
flows:
  master:
    - mvn -s ${MAVEN_HOME}/conf/settings.xml clean deploy -U -B
  default:
    - exposeVars(maven)
    - var(deployVersion = '%{MAVEN_VERSION.replace("-SNAPSHOT", "")}')
    - var(deployartfact= "${MAVEN_ARTIFACT_ID}-app")
    - call: build
  build:
    - exposeVars(maven)
    - mvn -s ${MAVEN_HOME}/conf/settings.xml clean deploy -U -B
  pr-build:
    - exposeVars(maven)
    - mvn -s ${MAVEN_HOME}/conf/settings.xml clean install -U -B
  release:
    - mvn -s ${MAVEN_HOME}/conf/settings.xml -B release:clean release:prepare release:perform release:update-versions